### ISSUE TITLE
Unable to import: "The version 059f07e for this integration can not be used with HACS."

### ISSUE THREAD

**Issue by napalmz** [Imou-OpenPlatform/Imou-Home-Assistant#1]
Trying to import integrations in HACS I get this error:
![image](https://github.com/user-attachments/assets/3c25dfa5-2846-4043-9f30-44186cba34cf)

**Home Assistant**
- Core: 2024.11.3
- Supervisor: 2024.11.4
- Operating System: 13.2
- Frontend: 20241106.2

**Comment by vnani12** [comment]
Same to me.
I tried importing it manual but after trying to install this is message I get:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by Imou-OpenPlatform** [comment]
Okay, we have resolved the issue. Thank you for bringing it up. Please use the latest version of the code

**Comment by napalmz** [comment]
I see no difference, stil doesn't work.
![image](https://github.com/user-attachments/assets/d70268d4-0f0a-4262-8334-6fc34e2cf523)

**Comment by Imou-OpenPlatform** [comment]
We have confirmed again that the code can run normally. If there are still issues, please ensure that the code has been updated to the latest version. If there are still issues, please check the log file to find the cause of the problem

**Comment by letienne** [comment]
same here, but with the latest commit:

"The version 2d6c8aa for this integration can not be used with HACS"

Are you sure that your repo is compatible with HACS?

**Comment by Imou-OpenPlatform** [comment]
Hello, we currently do not support installation through HACS. We will consider supporting it in the future. Please refer to the official website instructions for installation now. https://open.imoulife.com/book/guide/haDev.html

**Comment by Imou-OpenPlatform** [comment]
Hello everyone, we now support installation through HACS. Welcome to experience it.
